### ISSUE TITLE
Missing of model checkpoint

### ISSUE THREAD

**Issue by chikiuso** [Advocate99/DiffGesture#1]
Good morning,

  Thanks for your good work, I would like to have a try and run it, I got the following error when I run inference, do you have any idea how to fix it? or there is something missing? thanks :

FileNotFoundError: [Errno 2] No such file or directory: 'output/train_diffusion_ted/pose_diffusion_checkpoint_499.bin'

**Comment by chikiuso** [comment]
I just changed the path at the bottom of the test script as : 

ckpt_path = 'output/TED_Expressive_output/AE-cos1e-3/checkpoint_best.bin'

It runs, then it shows the following error message :  

Traceback (most recent call last):
  File "/Users/chikiuso/Downloads/DiffGesture/scripts/test_ted.py", line 542, in <module>
    main(mode, ckpt_path)
  File "/Users/chikiuso/Downloads/DiffGesture/scripts/test_ted.py", line 415, in main
    args, diffusion, lang_model, speaker_model, pose_dim = load_checkpoint_and_model(
  File "/Users/chikiuso/Downloads/DiffGesture/scripts/test_ted.py", line 46, in load_checkpoint_and_model
    lang_model = checkpoint['lang_model']
KeyError: 'lang_model'


It seems there is some parameter missing in the model? thanks.

**Comment by Advocate99** [comment]
Hi,

You can run training code to get the model. Then the model will be saved in the default directory.
Since the checkpoint in th AE dir is not the diffusion model, the path in the test script cannot be modified as the AE ckpt, which is used for metrics evaluation. Therefore, I would suggest following the instructions and running the training scripts first.

**Comment by chikiuso** [comment]
May I ask what gpu cluster or spec you used and how long did it take to train? thanks

**Comment by Advocate99** [comment]
> May I ask what gpu cluster or spec you used and how long did it take to train? thanks
The models can be trained on one 3090 GPU within one day.
You may follow the training instruction in README.
