### ISSUE TITLE
ValueError: unknown file extension: .mp4

### ISSUE THREAD

**Issue by ggg66** [Advocate99/DiffGesture#10]
Hello! Thanks for your outstanding work
I meet this error when I run python scripts/test_ted.py long:
ValueError: unknown file extension: .mp4
and it seems like in test_ted.py line 391.
I looked up some information and got the answer that pillow does not support MP4 format
Can you give me some advice?

**Comment by Advocate99** [comment]
Hi, I think this is related to the version of matplotlib animation.
I use matplotlib of version 3.3.4.
Maybe you could try changing the package version or saving the mp4 as other formats like .gif.

**Comment by ggg66** [comment]
Hello! I changed matplotlib version to 3.3.4 but it doesn't work, when I change the format to .gif, I meet this error:
File "scripts/test_ted.py", line 405, in create_video_and_save
    subprocess.call(cmd)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'
Should I install ffmpeg?
Thanks for your reply

**Comment by Advocate99** [comment]
Oh, yes. I think this is the reason and u should install ffmpeg first.

**Comment by TheCap-wa** [comment]
Do you mean I need to make this change？
parser.add("--train_data_path", type=list,default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_train")
    parser.add("--val_data_path", type=list,default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_val")
    parser.add("--test_data_path", type=list,default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_test")，But still return the same error
