### ISSUE TITLE
lmdb.Error: data/ted_dataset/lmdb_train: No such file or directory

### ISSUE THREAD

**Issue by dawn1007dx** [Advocate99/DiffGesture#11]
Traceback (most recent call last):
  File "scripts/train_ted.py", line 179, in <module>
    main({'args': _args})
  File "scripts/train_ted.py", line 133, in main
    train_dataset = SpeechMotionDataset(args.train_data_path[0],
  File "D:\anzbao-biancheng\githubproject\DiffGesture-main\scripts\data_loader\lmdb_data_loader.py", line 86, in __init__
    data_sampler = DataPreprocessor(lmdb_dir, preloaded_dir, n_poses_extended,
  File "D:\anzbao-biancheng\githubproject\DiffGesture-main\scripts\data_loader\data_preprocessor.py", line 30, in __init__
    self.src_lmdb_env = lmdb.open(clip_lmdb_dir, readonly=True, lock=False)
lmdb.Error: data/ted_dataset/lmdb_train: No such file or directory

**Comment by Advocate99** [comment]
Hi, have you finished the section installation & preparation?
You can follow this repo https://github.com/alvinliu0/HA2G to download the dataset.
If you have the datasets but still have this error, check the path.

**Comment by StefanoBraghetto** [comment]
Hey. Do we have to follow all the steps from readme.md of that repository?

I'm having the same issue, and did the sections: **TED Expressive Dataset** & **TED Gesture Dataset**
I am missing something else?
Thanks

**Comment by Advocate99** [comment]
> Hey. Do we have to follow all the steps from readme.md of that repository?
> 
> I'm having the same issue, and did the sections: **TED Expressive Dataset** & **TED Gesture Dataset** I am missing something else? Thanks

Hi, after doing that, could you check the path of downloaded dataset? Do you have this path (data/ted_dataset/lmdb_train)?

**Comment by Stefano-retinize** [comment]
@Advocate99 you are totally right. I was missing to create the folder: ted_dataset. Sorry for the dummy question. Thanks!

**Comment by StefanoBraghetto** [comment]
@Advocate99 you are totally right. I was missing to create the folder: ted_dataset. Sorry for the dummy question. Thanks!
