### ISSUE TITLE
Error while reading data from the mdb files using Pyarrow

### ISSUE THREAD

**Issue by yttehs** [Advocate99/DiffGesture#14]
Hi,

I am getting an error when I try deserializing the mdb files from both ted_gesture and ted_expressive datasets. 

A sample code block to generate the error:
```python
import lmdb
import pyarrow

# Path to the LMDB database file
db_path = '/path/to/mdb/'

# Open the LMDB environment
env = lmdb.open(db_path, readonly=True)  # Open in read-only mode

# Begin a read-only transaction
with env.begin(write=False) as txn:
    # Open a cursor to iterate over the records in the database
    cursor = txn.cursor()

    # Iterate over the records
    for key, value in cursor:
        # Deserialize the value using pyarrow
        data = pyarrow.deserialize(value)

# Close the LMDB environment
env.close()
``` 
<details><summary>Error Message</summary>
<p>

Traceback (most recent call last):
  File "tmp.py", line 19, in <module>
    data = pyarrow.deserialize(value)
  File "pyarrow/serialization.pxi", line 550, in pyarrow.lib.deserialize
  File "pyarrow/serialization.pxi", line 556, in pyarrow.lib._deserialize
  File "pyarrow/serialization.pxi", line 285, in pyarrow.lib.SerializedPyObject.deserialize
  File "pyarrow/error.pxi", line 129, in pyarrow.lib.check_status
pyarrow.lib.ArrowSerializationError: Cannot convert string: "" to int8_t

</p>
</details> 

To make sure that this issue is not because of corrupted mdb files, I re-downloaded the files. But, unfortunately, the issue persists.

The issue is similar to: https://github.com/Advocate99/DiffGesture/issues/3#issuecomment-1592405812

Please can you help me out with this issue.

Thank you in advance:)

P.S. serialize() and deserialize() functions have been removed from the latest pyarrow version (12.0.1), so I am using pyarrow  version 11.0.0 (the version mentioned in the requirements.txt is pyarrow==0.14.1. But this version does not exist).

**Comment by sunny123gaoao** [comment]
I tried and it seems that only older versions of PyArrow can be successfully installed.You can find the .whl file for PyArrow on the PyPI website. You can directly download it from the following link: (https://pypi.org/project/pyarrow/0.15.0/#files).

Please note that the provided .whl file supports Python 3.7 only.
