### ISSUE TITLE
我们项目可以实现 语音驱动图像中人物运动吗，类似与这个项目实现（ANGIE），或者说这个项目代码最近会发布吗

### ISSUE THREAD

**Issue by zhanghongyong123456** [Advocate99/DiffGesture#15]
https://alvinliu0.github.io/projects/ANGIE

**Comment by Advocate99** [comment]
语音驱动图像空间的动画需要构建一套新的框架和流程，DiffGesture是用conditional diffusion驱动一种3D表征空间的motion.
语音驱动的图像动画生成有一些GAN based的工作，可以看一下。你提到的这个项目我没有参与，我不太清楚。
