### ISSUE TITLE
How to run a new dataset with DiffGesture

### ISSUE THREAD

**Issue by ggg66** [Advocate99/DiffGesture#16]
Thanks for your great job!
I have a new Dataset with .bvh and .wav. 
I have a question that how to match your model.
thanks!

**Comment by Advocate99** [comment]
Hi, for the new format, the dataloader is needed to return the pose sequence and the audio feature.
You can check the files lmdb_data_loader.py in scripts.dataloader and train_ted.py in scripts.utils.
The loader should give synchronized pose vectors and audio features. For the audio features, the shape should be time_dimension \times feature_dimension, and multiple types of feature (mfcc, spectrum feature).

**Comment by ggg66** [comment]
Thanks for your answer!

**Comment by ggg66** [comment]
I want to open 'data_gesture_data/lmdb_train' to see what 'pose_seq' looks like, but I can't open it with Access. What information should be included in the pose sequence?

**Comment by Advocate99** [comment]
Hi, it is a tensor of the shape [bs, pose_length, pose_dim].

**Comment by TrainColab** [comment]
Hi, thank you for this interesting project. I just want to know how to generate an output as an image (not sequences of landmarks). Thank you again.

**Comment by Advocate99** [comment]
Hi, to output images, you can simply add some codes in the animate function in the test script. Just use fig.savefig(path) after the lines of axes setting code.

**Comment by ggg66** [comment]
I have another question, 
why is the video length set between 50 and 90 when running
python scripts/test_ted.py long
thanks for your reply

**Comment by Advocate99** [comment]
Hi, because I want to control the length when I test the long videos.
You can freely edit that.

**Comment by ggg66** [comment]
How do you add the start_time and end_time of a video to an LMDB file？ thanks for your reply

**Comment by Advocate99** [comment]
The values are set in the procedure of data collection. The information is processed and saved as the meta-info.

**Comment by ggg66** [comment]
When I running 
python scripts/train_ted.py --config=config/pose_diffusion_ted.yml, 
I used pdb for debugging and found that the data loaded by the dataloader is all zeros. Do you have any suggestions?thanks！

**Comment by ggg66** [comment]
And I noticed that the train_cache file is only 8KB, and I haven't made any changes to the dataloader code.

**Comment by Advocate99** [comment]
Hi, are you using your own data?
I haven't met that and sorry that I do not have suggestion.

**Comment by ggg66** [comment]
I am using the TED_Gesture dataset, as I have observed a similar issue with my own dataset. However, I still encounter the same problem even when using the TED_Gesture data

**Comment by Advocate99** [comment]
So you cannot start the training of ted gesture due to the dataset issue? Is it related to the version of some packages? I am not sure how to solve that.

**Comment by ggg66** [comment]
I have used your requirements.txt. My Python version is 3.7.2. May I know your Python version? Are there any specific version requirements for other packages that I need to be aware of？thanks！

**Comment by Advocate99** [comment]
Python 3.6.13, torch 1.10.2, librosa 0.9.1, lmdb 0.96, soundfile 0.10.3
