### ISSUE TITLE
Are diffgesture's experiment results tested on validation set?

### ISSUE THREAD

**Issue by Darius-H** [Advocate99/DiffGesture#17]
I found that Diffgesture's metrics evaluation code uses valset but not testset.https://github.com/Advocate99/DiffGesture/blob/30c3356b2317133c6020d9396d02bb263fdc09ed/scripts/test_expressive.py#L526
Are the results in paper also tested on valset?

**Comment by Advocate99** [comment]
Hi. Yes, we use the validation set following former codebases.



---Original---
From: ***@***.***&gt;
Date: Fri, Oct 27, 2023 13:49 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Advocate99/DiffGesture] Are diffgesture's experiment results testedon validation set? (Issue #17)




 
I found that Diffgesture's metrics evaluation code uses valset but not testset.https://github.com/Advocate99/DiffGesture/blob/30c3356b2317133c6020d9396d02bb263fdc09ed/scripts/test_expressive.py#L588
 Are the results in paper also tested on valset?
