### ISSUE TITLE
Real Pose Generate

### ISSUE THREAD

**Issue by qingyuanxingsi** [Advocate99/DiffGesture#19]
Thanks for your great work, how can I generate real poses corresponding to the openpose format? I found that output_poses generated by inference script are quite small numbers

**Comment by Advocate99** [comment]
Hi, in our generation space, the poses are in the format of direction vectors. So, if we know the length of the controlling bones, we can convert the vectors to the positions of the bones.
You can check the code scripts/utils/data_utils_expressive.py .
