### ISSUE TITLE
lang_model and fasttext？

### ISSUE THREAD

**Issue by thinkyang88** [Advocate99/DiffGesture#20]
Hello, I have two questions:
The first question is what is the function of lang_model? There are two places indicating lang_model,
1. lang_model = checkpoint['lang_model'] and
2. with open(vocab_cache_path, 'rb') as f:
         lang_model = pickle.load(f)
The second question is, is the fasttext model used in the inference process? I can’t find where to call it?

**Comment by Advocate99** [comment]
Hi, in training the language model is useless because we only use the audio modality. In inference, the model can be used to provide the speaking words. And in inference, the language model saved along with the saved ckpt is used and that model uses the fasttext and build the vocab in training.

**Comment by thinkyang88** [comment]
so in inference, only audio and initial pose are needed to generate gestures for new audio? No text message is required.

**Comment by Advocate99** [comment]
yes
