### ISSUE TITLE
Why use the val dataset to do the model testing?

### ISSUE THREAD

**Issue by Yixin-Shen-1218** [Advocate99/DiffGesture#21]
Hi,

If I'm not mistaken, both HA2G and DiffGesture use the val dataset as the dataset for the testing model. While this doesn't really affect performance comparisons between models, shouldn't we generally be using the test dataset?

Thanks in advance!

**Comment by Advocate99** [comment]
Hi. Thanks for your interest. Yes, we use the validation set in the code and compare all the methods in that split. It is simply because the code of HA2G uses that for validation and we follow it mainly for fairly comparison.

**Comment by Yixin-Shen-1218** [comment]
Thanks for your reply!
