### ISSUE TITLE
Regarding dataset path configuration issues

### ISSUE THREAD

**Issue by TheCap-wa** [Advocate99/DiffGesture#24]
Hello author, I have set my own defined file path, but in the configuration file path function, train_dataset=SpeedMotionDataset (args. train_data_path [0]),
N-poses=args. n-poses,
Subdivision_stride=args. subdivision_stride,
Pose resampling_fps=args. motion resampling frame,
Mean dir_vec=mean dir_vec,
Mean pose=args. mean pose,
Remove_wordting=(args. input_context=='text ')
）
Args. train_data_path [0], which only displays the first letter "E" of the file path, and I tried to change it to args. train_data_path, but there were still errors where I couldn't find the dataset. I don't know how to solve this problem

**Comment by Advocate99** [comment]
Hi, in my code the path is a list so we need index [0]. Just casually change the relative code to make it work and pay attention to the type of the variables.
What is the error you mentioned?

**Comment by TheCap-wa** [comment]
Hi, this is the path information I configured，
def parse_args():
    parser = configargparse.ArgParser()
    parser.add('-c', '--config', default=r"E:\ZHY\DiffGesture-main\config\pose_diffusion_ted.yml, is_config_file=True", help='Config file path')
    parser.add("--name", type=str, default="pose_diffusion")
    # parser.add("--train_data_path", default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_train", type=str)
    parser.add("--train_data_path", action="append",default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_train")
    parser.add("--val_data_path", action="append",default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_val")
    parser.add("--test_data_path", action="append",default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_test")
    parser.add("--model_save_path", default=r"E:\ZHY\DiffGesture-main\output\train_diffusion_ted")
    parser.add("--pose_representation", type=str, default='3d_vec')
    parser.add("--mean_dir_vec", action="append", type=list, nargs='*',default=[ 0.0154009, -0.9690125, -0.0884354, -0.0022264, -0.8655276, 0.4342174, -0.0035145, -0.8755367, -0.4121039, -0.9236511, 0.3061306, -0.0012415, -0.5155854,  0.8129665,  0.0871897, 0.2348464,  0.1846561,  0.8091402,  0.9271948,  0.2960011, -0.013189 ,  0.5233978,  0.8092403,  0.0725451, -0.2037076, 0.1924306,  0.8196916])
    parser.add("--mean_pose", action="append", type=float, nargs='*',default= [ 0.0000306,  0.0004946,  0.0008437,  0.0033759, -0.2051629, -0.0143453,  0.0031566, -0.3054764,  0.0411491,  0.0029072, -0.4254303, -0.001311 , -0.1458413, -0.1505532, -0.0138192, -0.2835603,  0.0670333,  0.0107002, -0.2280813,  0.112117 , 0.2087789,  0.1523502, -0.1521499, -0.0161503,  0.291909 , 0.0644232,  0.0040145,  0.2452035,  0.1115339,  0.2051307])
    parser.add("--random_seed", type=int, default=-1)
    parser.add("--save_result_video", type=str2bool, default=True)

    # word embedding
    parser.add("--wordembed_path", type=str, default=r"E:\ZHY\DiffGesture-main\data\fasttext\crawl-300d-2M-subword.bin")
    parser.add("--wordembed_dim", type=int, default=300)
    parser.add("--freeze_wordembed", type=str2bool, default=False)

    # model
    parser.add("--model", type=str, default='pose_diffusion')
    parser.add("--epochs", type=int, default=500)
    parser.add("--batch_size", type=int, default=128)
    parser.add("--hidden_size", type=int, default=300)
    parser.add("--input_context", type=str, default='audio')

    # dataset
    parser.add("--motion_resampling_framerate", type=int, default=15)
    parser.add("--n_poses", type=int, default=34)
    parser.add("--n_pre_poses", type=int, default=4)
    parser.add("--subdivision_stride", type=int, default=10)
    parser.add("--loader_workers", type=int, default=4)

    parser.add("--pose_dim", type=int, default=27)
    parser.add("--latent_dim", type=int, default=128)

    parser.add("--diff_hidden_dim", type=int, default=256)
    parser.add("--block_depth", type=int, default=8)

    # training
    parser.add("--learning_rate", type=float, default=0.0005)

    parser.add("--classifier_free", type=str2bool, default=True)
    parser.add("--null_cond_prob", type=float, default=0.1)

    # eval
    parser.add("--eval_net_path", type=str, default=r"E:\ZHY\DiffGesture-main\output\train_h36m_gesture_autoencoder"
                                                    r"\gesture_autoencoder_checkpoint_best.bin")

    args = parser.parse_args()
    return args，The error returned is E:�Ҳ���ָ����·����,It can be seen that it displays the E drive and a bunch of garbled characters behind it

**Comment by TheCap-wa** [comment]
Hi, this is the file information I configured，
def parse_args():
    parser = configargparse.ArgParser()
    parser.add('-c', '--config', default=r"E:\ZHY\DiffGesture-main\config\pose_diffusion_ted.yml, is_config_file=True", help='Config file path')
    parser.add("--name", type=str, default="pose_diffusion")
    # parser.add("--train_data_path", default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_train", type=str)
    parser.add("--train_data_path", action="append",default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_train")
    parser.add("--val_data_path", action="append",default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_val")
    parser.add("--test_data_path", action="append",default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_test")
    parser.add("--model_save_path", default=r"E:\ZHY\DiffGesture-main\output\train_diffusion_ted")
    parser.add("--pose_representation", type=str, default='3d_vec')
    parser.add("--mean_dir_vec", action="append", type=list, nargs='*',default=[ 0.0154009, -0.9690125, -0.0884354, -0.0022264, -0.8655276, 0.4342174, -0.0035145, -0.8755367, -0.4121039, -0.9236511, 0.3061306, -0.0012415, -0.5155854,  0.8129665,  0.0871897, 0.2348464,  0.1846561,  0.8091402,  0.9271948,  0.2960011, -0.013189 ,  0.5233978,  0.8092403,  0.0725451, -0.2037076, 0.1924306,  0.8196916])
    parser.add("--mean_pose", action="append", type=float, nargs='*',default= [ 0.0000306,  0.0004946,  0.0008437,  0.0033759, -0.2051629, -0.0143453,  0.0031566, -0.3054764,  0.0411491,  0.0029072, -0.4254303, -0.001311 , -0.1458413, -0.1505532, -0.0138192, -0.2835603,  0.0670333,  0.0107002, -0.2280813,  0.112117 , 0.2087789,  0.1523502, -0.1521499, -0.0161503,  0.291909 , 0.0644232,  0.0040145,  0.2452035,  0.1115339,  0.2051307])
    parser.add("--random_seed", type=int, default=-1)
    parser.add("--save_result_video", type=str2bool, default=True)

    # word embedding
    parser.add("--wordembed_path", type=str, default=r"E:\ZHY\DiffGesture-main\data\fasttext\crawl-300d-2M-subword.bin")
    parser.add("--wordembed_dim", type=int, default=300)
    parser.add("--freeze_wordembed", type=str2bool, default=False)

    # model
    parser.add("--model", type=str, default='pose_diffusion')
    parser.add("--epochs", type=int, default=500)
    parser.add("--batch_size", type=int, default=128)
    parser.add("--hidden_size", type=int, default=300)
    parser.add("--input_context", type=str, default='audio')

    # dataset
    parser.add("--motion_resampling_framerate", type=int, default=15)
    parser.add("--n_poses", type=int, default=34)
    parser.add("--n_pre_poses", type=int, default=4)
    parser.add("--subdivision_stride", type=int, default=10)
    parser.add("--loader_workers", type=int, default=4)

    parser.add("--pose_dim", type=int, default=27)
    parser.add("--latent_dim", type=int, default=128)

    parser.add("--diff_hidden_dim", type=int, default=256)
    parser.add("--block_depth", type=int, default=8)

    # training
    parser.add("--learning_rate", type=float, default=0.0005)

    parser.add("--classifier_free", type=str2bool, default=True)
    parser.add("--null_cond_prob", type=float, default=0.1)

    # eval
    parser.add("--eval_net_path", type=str, default=r"E:\ZHY\DiffGesture-main\output\train_h36m_gesture_autoencoder"
                                                    r"\gesture_autoencoder_checkpoint_best.bin")

    args = parser.parse_args()
    return args
The error returned is lmdb.Error: E: ϵͳ�Ҳ���ָ����·����，It can be seen that the returned file is the E drive and a bunch of garbled code behind it. I think it may be a problem with my configuration?

**Comment by Advocate99** [comment]
It seems that this is wrong: default=r"E:\ZHY\DiffGesture-main\config\pose_diffusion_ted.yml, is_config_file=True",
here is_confit_file=True is included in your file name.
Besides, for those variable you set default values which are str, not list, remove the append action.

**Comment by TheCap-wa** [comment]
Do you mean I need to make this change？
parser.add("--train_data_path", type=list,default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_train")
    parser.add("--val_data_path", type=list,default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_val")
    parser.add("--test_data_path", type=list,default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_test")，但是还是报相同的错误

**Comment by TheCap-wa** [comment]
Do you mean I need to make this change？
parser.add("--train_data_path", type=list,default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_train")
parser.add("--val_data_path", type=list,default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_val")
parser.add("--test_data_path", type=list,default=r"E:\ZHY\DiffGesture-main\data\ted_dataset\lmdb_test")，But still return the same error.

**Comment by TheCap-wa** [comment]
Hi，I have made the modifications as per your request
def parse_args():
    parser = configargparse.ArgParser()
    parser.add('-c', '--config', default=True, is_config_file=r"E:\ZHY\DiffGesture-main\config\pose_diffusion_ted.yml", help='Config file path')
    parser.add("--name", type=str, default="main")
    parser.add("--train_data_path", action="append")
    parser.add("--val_data_path", action="append")
    parser.add("--test_data_path", action="append")
    parser.add("--model_save_path", default=True)
    parser.add("--pose_representation", type=str, default='3d_vec')
    parser.add("--mean_dir_vec", action="append", type=float, nargs='*')
    parser.add("--mean_pose", action="append", type=float, nargs='*')
    parser.add("--random_seed", type=int, default=-1)
    parser.add("--save_result_video", type=str2bool, default=True)

    # word embedding
    parser.add("--wordembed_path", type=str, default='None')
    parser.add("--wordembed_dim", type=int, default=100)
    parser.add("--freeze_wordembed", type=str2bool, default=False)

    # model
    parser.add("--model", type=str, default=True)
    parser.add("--epochs", type=int, default=10)
    parser.add("--batch_size", type=int, default=50)
    parser.add("--hidden_size", type=int, default=200)
    parser.add("--input_context", type=str, default='audio')

    # dataset
    parser.add("--motion_resampling_framerate", type=int, default=24)
    parser.add("--n_poses", type=int, default=50)
    parser.add("--n_pre_poses", type=int, default=5)
    parser.add("--subdivision_stride", type=int, default=5)
    parser.add("--loader_workers", type=int, default=0)

    parser.add("--pose_dim", type=int, default=True)
    parser.add("--latent_dim", type=int, default=128)

    parser.add("--diff_hidden_dim", type=int, default=True)
    parser.add("--block_depth", type=int, default=8)

    # training
    parser.add("--learning_rate", type=float, default=0.001)

    parser.add("--classifier_free", type=str2bool, default=False)
    parser.add("--null_cond_prob", type=float, default=None)

    # eval
    parser.add("--eval_net_path", type=str, default='')

    args = parser.parse_args()
    return args
I only changed the later require to default, but there are still errors is TypeError: expected str, bytes or os.PathLike object, not bool.

**Comment by Advocate99** [comment]
Hi, the error is clear. You should change default=r"E:\ZHY\DiffGesture-main\config\pose_diffusion_ted.yml, is_config_file=True", to default=r"E:\ZHY\DiffGesture-main\config\pose_diffusion_ted.yml", is_config_file=True,
It says TypeError because you set is_config_file as str.
Besides, for those variable you set default values which are str, not list, remove the append action. It seems you also misunderstand the meaning of this sentence. Anyway, you just need to pass the value correctly.

**Comment by TheCap-wa** [comment]
My Python code foundation is too weak

**Comment by Advocate99** [comment]
Keep it up

**Comment by ChebliAlamiAhmed** [comment]
> Hi, the error is clear. You should change default=r"E:\ZHY\DiffGesture-main\config\pose_diffusion_ted.yml, is_config_file=True", to default=r"E:\ZHY\DiffGesture-main\config\pose_diffusion_ted.yml", is_config_file=True, It says TypeError because you set is_config_file as str. Besides, for those variable you set default values which are str, not list, remove the append action. It seems you also misunderstand the meaning of this sentence. Anyway, you just need to pass the value correctly.

please if you already implement the project, show me some demo videos.
