### ISSUE TITLE
pyarrow error

### ISSUE THREAD

**Issue by Benwang-chen** [Advocate99/DiffGesture#3]
I follow the requirement in 3090Ti.

I try to install the pyarrow==0.14.1, but I can't install it.

ERROR: Could not find a version that satisfies the requirement pyarrow==0.14.1 (from versions: 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.13.0, 0.14.0, 0.15.1, 0.16.0, 0.17.0, 0.17.1, 1.0.0, 1.0.1, 2.0.0, 3.0.0, 4.0.0, 4.0.1, 5.0.0, 6.0.0, 6.0.1, 7.0.0, 8.0.0, 9.0.0, 10.0.0, 10.0.1, 11.0.0)
ERROR: No matching distribution found for pyarrow==0.14.1

The version seems already updated. So I install the latest version. When I run the following code:

https://github.com/Advocate99/DiffGesture/blob/ab54c56cbbaa331463d51ffcc429caf37a260dda/scripts/data_loader/data_preprocessor_expressive.py#L46

I am getting the following error:

Exception has occurred: OSError
Expected IPC message of type unknown but got unknown

 Do you have any questions or detailed configuration?

**Comment by Advocate99** [comment]
Hi,
I installed pyarrow 0.14.1 in my environment. I think you may try installing older version like 0.14.0 or 0.15.1?

**Comment by xljh0520** [comment]
Hello, I have encountered the same problem as well. Have you managed to solve this bug? I have tried installing both pyarrow versions 0.14.0 and 0.15.1, but I keep getting errors during installing.

**Comment by kiranchhatre** [comment]
this worked for me:

pyarrow==0.14.1
lmdb==0.96
librosa==0.9.2
numpy==1.19.0

on python version 3.7.12
CUDA version: 11.7
PyTorch version: 1.13.1

**Comment by emadkavousi** [comment]
hi . i am trying to run you project but i have issues with pyarrow .
the pyarrow== 0.14.0 only can be install on python 3.6 and it give me an error on other versions of python and I have RTX3060 and the cuda version for this series of graphic card  is cuda => 11.0 and the latest cuda version that supported by pytorch in python 3.6 is cuda 10.x on pytroch 1.10.2 and there isnt any way to install cuda 11 supported version of pytorch on python 3.6 .
please tell me how can I run your project ? How did you manage to run your project ?
