### ISSUE TITLE
[DiffGesture]

### ISSUE THREAD

**Issue by cyk990422** [Advocate99/DiffGesture#4]
Hello, Dr. Zhu!
This is a very outstanding job, and it has aroused my great interest.
But I have a small problem. I found that the maximum n_pose in the dataset ted_gesture_dataset seems to be fixed to 42. Is it correct that we use 34 during training? Is there a way to train longer frames (such as 64 frames, 128 frames)?

**Comment by Advocate99** [comment]
Hi, thanks for your interest.
We use 34 as the num_pose and the parameter is controlled with the config file and the data loader code.
42 is the (J-1) for TED Expressive dataset and is fixed in this dataset. And the number 42 is not used in the config and the data loader.
After training, the model can generate poses with the unit length as a clip under the conditions. Then we can generate long sequences with auto-regressive generation, where the last poses of the last clip can be used as the pre-poses of the next clip. We find generating longer frames achieves great performances and in fact, we will also investigate new ways for better long sequences generation.
In our paper, we show the metrics on the clip generation and compare the results with baselines of the same clip setting (clip length, the number of pre-poses) to make a fair comparison.

**Comment by cyk990422** [comment]
Thank you for your explanation！

**Comment by cyk990422** [comment]
Hello, Dr. Chu!
Sorry to bother you again, I discovered during the training of your model that my loss has a sudden increase and then a gradual decrease. Did this happen when you were training?
After I ran 500 epochs according to your code, the results on TED_Expressive seem to be far from the FGD of the table in the text.
Here are the results of my trained model:
[VAL] joint mae: 0.10452, accel diff: 0.04005, FGD: 9.875, diversity_score: 185.041, BC: 0.724, feat_D: 153.261 / 23103.5s

**Comment by Advocate99** [comment]
Hi.
For the training, the loss gradually decreases after some epoches is normal.
Did you run the orginal expressive config and run the test script?
The FGD is strange but the div and the bc are normal. In my experiments, the FGD metrics for Expressive dataset are ranging from 2 to 3.x and the results are quite robust.

**Comment by cyk990422** [comment]
Yes, I directly ran the script you gave to train a model for 500 epochs:
python scripts/train_expressive.py --config=config/pose_diffusion_expressive.yml
Also used the evaluation command and configuration you provided:
python scripts/test_expressive.py eval

**Comment by cyk990422** [comment]
For the dataset of ted expressive, I directly downloaded the preprocessed data in H2G.

**Comment by Advocate99** [comment]
I am not sure if there are somewhere strange like package version that affects the fgd and I will check what's wrong.
Can you try generating short videos and have a look at whether the results are normal?
You can also try running the TED dataset, or training a model on Expressive again to find if the metrics change dramatically.

**Comment by cyk990422** [comment]
Hello Dr. Zhu.
I'm sorry that something unexpected happened yesterday and I couldn't reply to your message in time. In my recurrence experiment, the results of TED Gesture can be perfectly reproduced to the results of the paper, but the gap between FGD in TED Expressive is large, and I am trying to retrain.
The short visualization on TED Expressive is as follows:

https://user-images.githubusercontent.com/42002060/232399954-bd26b232-b21c-4235-ab91-8524126116b9.mp4

It turned out that there seemed to be no major problems.
I'll see how it turns out after retraining, thanks doc!

**Comment by Advocate99** [comment]
Hi, since the TED Gesture exps work well, I think there are no obvious errors concerning envioronment issues.
But it is quite strange that the FGD on Expressive has a big volatility and I have not observed that before.
I am running the Expressive exps on a new server with a different environment and I will see the metrics then.
Thanks.

**Comment by cyk990422** [comment]
Hello, Dr. Zhu, I successfully reproduced your results, I think there should be some small mistakes in my previous step. Thank you so much for your patience!
I would like to ask whether the input expression of your gesture can use 3D location or rot6D. even the angle of rotation?

**Comment by Advocate99** [comment]
Hi, nice to hear that.
BTY, I also ran the code on a new environment and I found the results are normal.
Yes, introducing more complex input for more complex generation is the correct way and some other inputs like 3D location, rot6D, and other key representation in graphics can serve as the inputs.
In fact, there are some papers which use diffusion models for 3D generation (scene, motion, human faces, and graphics models) and they apply similar ways to do various tasks. I think the results are quite great.
Thanks.

**Comment by cyk990422** [comment]
Sorry to bother you again, Dr. Zhu. I would like to ask if you have studied the BEAT dataset. Do you know whether the rotation angle given in his official preprocessing code is an axial angle or an Euler angle?

**Comment by Advocate99** [comment]
Sorry that I don't know that. I think that can be determined with some tests.
We haven't investigate that dataset. But it is an interesting dataset and I have another project which may also involve that in the future.

**Comment by cyk990422** [comment]
Thank you very much for your prompt and patient reply, which helped me a lot as a beginner.

**Comment by Advocate99** [comment]
Thanks～

**Comment by wang-zm18** [comment]
Hello, I have the same problem about why 34 joints are chosen for training instead of all 43 joints? And how to visualize  all 43 joints  by only utilizing 34 joints during the inference  phase？ Thank you in advance!

**Comment by Advocate99** [comment]
> Hello, I have the same problem about why 34 joints are chosen for training instead of all 43 joints? And how to visualize all 43 joints by only utilizing 34 joints during the inference phase？ Thank you in advance!

Hi, 43 is the joint number and 34 is the frame number.

**Comment by wang-zm18** [comment]
In pose_diffusion_expressive.yml, n_poses is specified as 34 instead of 43. Is there any information about specifying the frame number as 34？

**Comment by Advocate99** [comment]
The number of frame is n_poses. The 43 corresponds to the data. Pose_dim equals to 3*(J-1).

**Comment by wang-zm18** [comment]
Ok, I see! Thank you!
