### ISSUE TITLE
About reproduction of the experiment result in Paper.

### ISSUE THREAD

**Issue by robingg1** [Advocate99/DiffGesture#6]
Thanks for you outstanding work! I am very interested in this method and thanks for your hard work. However, for the uploaded code I have ran the training code for Ted Gesture dataset and got worser result compared with the result in Paper. I am asking whether there are some changes need to perform to reproduce the best result, also is the checkpoint at 499th epoch produces that result in Paper ?

**Comment by Advocate99** [comment]
Hi, what's the results when you ran test script for TED Gesture?
The 499th ckpt is for evaluation empirically. The results can be a little different when running several times and overall the performances are robust. In my former experiements, normally the FGD may differ from 1.x to 2.x.
Thanks.

**Comment by robingg1** [comment]
Thanks for answering the problem. I got FGD of around 2.x several times and it seems normal then. Also I want to ask did you try to increase batch size for your experiment ?

**Comment by Advocate99** [comment]
Hi, since the experiments do not cost too much memory, it is okay to increase the bs. And we do not observe clear performance drop with larger bs.
Then we just fixed bs the same as the former works.
