### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/ted_expressive_dataset/vocab_cache.pkl'

### ISSUE THREAD

**Issue by bobo-wmdigit** [Advocate99/DiffGesture#9]
Is it necessary for me to download HA2G dataset?

**Comment by Advocate99** [comment]
Hi, you can check the Installtion step 4 in ReadMe and the links are included in https://github.com/alvinliu0/HA2G.

**Comment by Advocate99** [comment]
Yes, it is necessary to download the datasets in HA2G since we use the same datasets.
